"""From-scratch ElGamal encryption over a large cyclic group.

- Group: a Schnorr subgroup of a 2048-bit prime p, with a 256-bit prime-order
  subgroup generated by g (DSA-style domain parameters). This gives ~128-bit
  security for the subgroup discrete-log problem.
- Keypair: x (private) random in [1, q-1], y = g^x mod p (public).
- Encrypt(m): pick k random in [1, q-1]; c1 = g^k, c2 = m * y^k (mod p).
- Decrypt:   m = c2 * (c1^x)^-1 (mod p).
- ElGamal is used EXCLUSIVELY for lightweight posts and direct messages, which
  keeps ciphertext blocks small enough for pure-Python modular math.
"""

import json

from .math_utils import generate_prime, is_probable_prime, modinv, random_int


class ElGamalDomain:
    """Shared domain parameters (p, q, g) for the whole platform."""

    def __init__(self, p: int, q: int, g: int):
        self.p = p
        self.q = q
        self.g = g

    def generate_keypair(self) -> dict:
        """Generate an ElGamal keypair {"x": private, "y": public}."""
        x = random_int(2, self.q - 1)
        y = pow(self.g, x, self.p)
        return {"x": x, "y": y}

    def encrypt(self, public_y: int, plaintext: bytes, block_size: int = 200) -> bytes:
        """Encrypt ``plaintext`` to public key ``public_y``.

        Each plaintext block is framed as 2-byte length + data + zero padding to
        a fixed frame size (2 + block_size), converted to an integer m (< p),
        then ElGamal-encrypted. The ciphertext starts with a 2-byte header
        carrying the block size so decrypt can locate each frame. Output per
        block is (c1 || c2), each modulus_bytes(p) long.
        """
        p, g, q = self.p, self.g, self.q
        k_bytes = (p.bit_length() + 7) // 8
        if block_size + 2 > k_bytes:  # frame must fit below the modulus
            block_size = k_bytes - 2

        out = block_size.to_bytes(2, "big")  # header: block size used
        for i in range(0, len(plaintext), block_size):
            chunk = plaintext[i:i + block_size]
            framed = len(chunk).to_bytes(2, "big") + chunk + b"\x00" * (block_size - len(chunk))
            m = int.from_bytes(framed, "big")
            k = random_int(2, q - 1)
            c1 = pow(g, k, p)
            c2 = (m * pow(public_y, k, p)) % p
            out += c1.to_bytes(k_bytes, "big") + c2.to_bytes(k_bytes, "big")
        return out

    def decrypt(self, private_x: int, ciphertext: bytes) -> bytes:
        """Decrypt an ElGamal ciphertext with private key ``private_x``."""
        p = self.p
        k_bytes = (p.bit_length() + 7) // 8
        if len(ciphertext) < 2 or (len(ciphertext) - 2) % (2 * k_bytes) != 0:
            raise ValueError("malformed ciphertext length")

        block_size = int.from_bytes(ciphertext[:2], "big")
        frame_len = 2 + block_size
        out = b""
        body = ciphertext[2:]
        for i in range(0, len(body), 2 * k_bytes):
            c1 = int.from_bytes(body[i:i + k_bytes], "big")
            c2 = int.from_bytes(body[i + k_bytes:i + 2 * k_bytes], "big")
            if c1 >= p:
                raise ValueError("ciphertext block out of range")
            s = pow(c1, private_x, p)          # shared secret = g^(k*x)
            m = (c2 * modinv(s, p)) % p        # m = c2 * s^-1
            full = m.to_bytes(k_bytes, "big")
            frame = full[k_bytes - frame_len:]  # frame is right-aligned
            n = int.from_bytes(frame[:2], "big")
            out += frame[2:2 + n]
        return out


def load_domain(path, p_bits: int = 2048, q_bits: int = 256) -> ElGamalDomain:
    """Load the platform domain parameters, generating them on first use.

    If the cached file exists it is used as-is; otherwise a fresh Schnorr group
    is generated with the requested sizes and cached to ``path``.
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            d = json.load(f)
        return ElGamalDomain(int(d["p"], 16), int(d["q"], 16), int(d["g"], 16))
    except (FileNotFoundError, KeyError, ValueError):
        return generate_and_save_domain(path, p_bits=p_bits, q_bits=q_bits)


def generate_and_save_domain(path, p_bits: int = 2048, q_bits: int = 256) -> ElGamalDomain:
    """Generate a Schnorr group (one-time cost, cached to ``path``).

    q is a q_bits prime; p is a p_bits prime with p = k*q + 1; g = h^((p-1)/q)
    is an element of order q. Expected generation time is a few seconds.
    """
    q = generate_prime(q_bits)
    while True:
        k = random_int(2 ** (p_bits - q_bits - 1), 2 ** (p_bits - q_bits) - 1)
        p = k * q + 1
        if p.bit_length() != p_bits:
            continue
        if is_probable_prime(p, rounds=16):
            break

    g = 1
    while g == 1:
        h = random_int(2, p - 2)
        g = pow(h, (p - 1) // q, p)

    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"p": hex(p), "q": hex(q), "g": hex(g)}, f)

    return ElGamalDomain(p, q, g)


# --- Serialization ---------------------------------------------------------
# Format: ELGAMAL.PUBLIC.<p_hex>.<q_hex>.<g_hex>.<y_hex>
#         ELGAMAL.PRIVATE.<p_hex>.<q_hex>.<g_hex>.<y_hex>.<x_hex>
# The public string is self-contained (carries p, q, g) so a recipient can
# encrypt without needing the platform domain file.

def serialize_elgamal_public(domain, key: dict) -> str:
    return f"ELGAMAL.PUBLIC.{domain.p:x}.{domain.q:x}.{domain.g:x}.{key['y']:x}"


def serialize_elgamal_private(domain, key: dict) -> str:
    return f"ELGAMAL.PRIVATE.{domain.p:x}.{domain.q:x}.{domain.g:x}.{key['y']:x}.{key['x']:x}"


def parse_elgamal_public(s: str) -> dict:
    parts = s.split(".")
    if len(parts) != 6 or parts[0] != "ELGAMAL" or parts[1] != "PUBLIC":
        raise ValueError("invalid ElGamal public key string")
    return {"p": int(parts[2], 16), "q": int(parts[3], 16), "g": int(parts[4], 16), "y": int(parts[5], 16)}


def parse_elgamal_private(s: str) -> dict:
    parts = s.split(".")
    if len(parts) != 7 or parts[0] != "ELGAMAL" or parts[1] != "PRIVATE":
        raise ValueError("invalid ElGamal private key string")
    return {"p": int(parts[2], 16), "q": int(parts[3], 16), "g": int(parts[4], 16),
            "y": int(parts[5], 16), "x": int(parts[6], 16)}