"""Authentication & Identity: registration, login, 2FA, sessions.

- Registration encrypts the profile (email, name, contact) with the user's
  RSA-3072 public key before storage; the password is salted+hashed; RSA and
  ElGamal keypairs are generated by the KMM.
- Login verifies the salted hash, then enforces a mandatory TOTP step before
  issuing an HMAC-signed session token (>= 64 bits of entropy).
"""

import json
import time

from fastapi import APIRouter, Depends, HTTPException, Request
import pyotp
import segno

from ..core import config, security
from ..crypto import rsa, totp
from ..crypto.math_utils import random_bytes

router = APIRouter(prefix="/api/auth", tags=["auth"])


def _get_ctx(request: Request):
    return request.app.state.ctx


def _profile_payload(email: str, name: str, contact: str) -> bytes:
    return json.dumps({"email": email, "name": name, "contact": contact}).encode()


@router.post("/register")
def register(request: Request, body: dict):
    """Register a new user. All profile fields are RSA-encrypted before storage."""
    ctx = _get_ctx(request)
    username = (body.get("username") or "").strip()
    password = body.get("password") or ""
    email = (body.get("email") or "").strip()
    name = (body.get("name") or "").strip()
    contact = (body.get("contact") or "").strip()

    if not username or not password or not email:
        raise HTTPException(400, "username, password and email are required")
    if len(password) < 8:
        raise HTTPException(400, "password must be at least 8 characters")
    if ctx.db.fetchone("SELECT id FROM users WHERE username = ?", (username,)):
        raise HTTPException(409, "username already taken")

    now = int(time.time())
    hash_hex, salt_hex = security.hash_password(password)
    totp_secret = totp.generate_totp_secret()

    with ctx.db.transaction() as cur:
        cur.execute(
            """INSERT INTO users (username, password_hash, salt, totp_secret, role, is_suspended, created_at)
               VALUES (?, ?, ?, ?, 'user', 0, ?)""",
            (username, hash_hex, salt_hex, totp_secret, now))
        user_id = cur.lastrowid

    # KMM: generate RSA + ElGamal keypairs, store wrapped private keys.
    pub = ctx.key_manager.generate_user_keys(user_id)

    # Encrypt the profile with the user's RSA public key.
    rsa_pub = rsa.parse_rsa_public(pub["rsa_public"])
    ciphertext = rsa.rsa_encrypt_bytes(rsa_pub, _profile_payload(email, name, contact))
    ct_hex = ciphertext.hex()
    badge = security.make_integrity_badge("profile", user_id, ct_hex, ctx.secret)
    ctx.db.execute(
        "INSERT INTO profiles (user_id, encrypted, hmac, updated_at) VALUES (?, ?, ?, ?)",
        (user_id, ct_hex, badge, now))

    totp_obj = pyotp.TOTP(totp_secret)
    totp_uri = totp_obj.provisioning_uri(name=username, issuer_name="PrimeFeed")
    qr = segno.make(totp_uri)
    qr_svg_data_uri = qr.svg_data_uri(scale=5, border=2, light="#FFFFFF", dark="#000000")

    ticket = random_bytes(16).hex()
    ctx.pending_2fa[ticket] = {"user_id": user_id, "expires": now + 300}

    return {
        "ok": True,
        "user_id": user_id,
        "totp_secret": totp_secret,
        "totp_uri": totp_uri,
        "totp_qr": qr_svg_data_uri,
        "ticket": ticket,
        "message": "registration complete; scan QR code or enroll the TOTP secret in your authenticator app",
    }


@router.post("/login")
def login(request: Request, body: dict):
    """Step 1: verify credentials. Returns a pending-2FA ticket."""
    ctx = _get_ctx(request)
    username = (body.get("username") or "").strip()
    password = body.get("password") or ""

    row = ctx.db.fetchone(
        "SELECT id, password_hash, salt, is_suspended FROM users WHERE username = ?", (username,))
    if row is None or not security.verify_password(password, row["password_hash"]):
        raise HTTPException(401, "invalid credentials")
    if row["is_suspended"]:
        raise HTTPException(403, "account suspended")

    # Mandatory 2FA: issue a short-lived pending ticket bound to the user.
    ticket = random_bytes(16).hex()
    ctx.pending_2fa[ticket] = {"user_id": row["id"], "expires": int(time.time()) + 300}
    return {"ok": True, "requires_2fa": True, "ticket": ticket}


@router.post("/login/2fa")
def login_2fa(request: Request, body: dict):
    """Step 2: verify the TOTP code and issue an HMAC-signed session token."""
    ctx = _get_ctx(request)
    ticket = body.get("ticket") or ""
    code = body.get("code") or ""

    pending = ctx.pending_2fa.pop(ticket, None)
    if pending is None or pending["expires"] < int(time.time()):
        raise HTTPException(401, "2FA ticket expired or invalid")

    row = ctx.db.fetchone(
        "SELECT id, totp_secret, role, is_suspended FROM users WHERE id = ?", (pending["user_id"],))
    if row is None or row["is_suspended"]:
        raise HTTPException(403, "account unavailable")
    if not totp.verify_totp(row["totp_secret"], code, window=1):
        raise HTTPException(401, "invalid 2FA code")

    token = security.generate_session_token()
    signed = security.sign_session_token(token, row["id"], ctx.secret)
    now = int(time.time())
    ctx.db.execute(
        """INSERT INTO sessions (user_id, token_hash, created_at, expires_at, client_ip, user_agent)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (row["id"], security.token_hash(token), now, now + config.SESSION_TTL_SECONDS,
         request.client.host if request.client else None,
         request.headers.get("user-agent", "")[:200]))

    return {"ok": True, "session_token": signed, "role": row["role"]}


@router.post("/logout")
def logout(request: Request, body: dict):
    """Revoke the current session token."""
    ctx = _get_ctx(request)
    token = body.get("session_token") or ""
    user_id = security.verify_session_token(token, ctx.secret)
    if user_id is not None:
        ctx.db.execute("DELETE FROM sessions WHERE token_hash = ?", (security.token_hash(token),))
    return {"ok": True}


@router.get("/me")
def me(request: Request):
    """Return the current session's user id and role."""
    ctx = _get_ctx(request)
    urow = security.validate_session(ctx, request.headers.get("x-session-token", ""))
    if urow is None:
        raise HTTPException(401, "not authenticated")
    return {"user_id": urow["id"], "username": urow["username"], "role": urow["role"]}


@router.post("/change-password")
def change_password(request: Request, body: dict):
    """Change the caller's password. Revokes all sessions (forces re-login)."""
    ctx = _get_ctx(request)
    urow = security.validate_session(ctx, request.headers.get("x-session-token", ""))
    if urow is None:
        raise HTTPException(401, "not authenticated")

    current = body.get("current_password") or ""
    new = body.get("new_password") or ""
    row = ctx.db.fetchone("SELECT password_hash FROM users WHERE id = ?", (urow["id"],))
    if row is None or not security.verify_password(current, row["password_hash"]):
        raise HTTPException(400, "current password is incorrect")
    if len(new) < 8:
        raise HTTPException(400, "new password must be at least 8 characters")

    hash_hex, salt_hex = security.hash_password(new)
    ctx.db.execute("UPDATE users SET password_hash = ?, salt = ? WHERE id = ?", (hash_hex, salt_hex, urow["id"]))
    ctx.db.execute("DELETE FROM sessions WHERE user_id = ?", (urow["id"],))
    return {"ok": True, "message": "password changed; please sign in again"}